- name: Stop MicroK8s
  command: microk8s stop
  become: true
  listen: restart_microk8s

- name: Wait before restart
  pause:
    seconds: 15
  listen: restart_microk8s

- name: Start MicroK8s
  command: microk8s start
  become: true
  listen: restart_microk8s

- name: Wait for MicroK8s to be ready
  command: microk8s status --wait-ready --timeout 300
  become: true
  changed_when: false
  listen: restart_microk8s
