{{- if .Values.kafka.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: {{ .Values.kafka.replicas | default 1 }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.storage.size | default "5Gi" }}
        deleteClaim: false
  resources:
    requests:
      memory: {{ .Values.kafka.resources.requests.memory | default "512Mi" }}
      cpu: {{ .Values.kafka.resources.requests.cpu | default "250m" }}
    limits:
      memory: {{ .Values.kafka.resources.limits.memory | default "1Gi" }}
      cpu: {{ .Values.kafka.resources.limits.cpu | default "500m" }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: "enabled"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: "4.1.1"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30092
    config:
      auto.create.topics.enable: false
      default.replication.factor: 1
      min.insync.replicas: 1
      num.partitions: 8
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.retention.hours: 48
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics-config
          key: kafka-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}
